import functions as func

def help(userType):
# Prosedur untuk menampilkan panduan penggunaan sistem
    print()
    stopShow = False
    while not stopShow:
        if userType.lower() == "admin":
            print("================================ HELP ===================================")
            print("1. register - Untuk melakukan registrasi user baru.")
            print("2. login - Untuk melakukan login ke dalam sistem.")
            print("3. tambah_game - Untuk menambah game yang dijual pada toko.")
            print("4. ubah_game - Untuk mengubah data game yang dijual pada toko.")
            print("5. ubah_stok - Untuk mengubah stok game yang dijual pada toko.")
            print("6. list_game_toko - Untuk melihat daftar game yang dijual pada toko.")
            print("7. search_game_at_store - Untuk mencari sebuah game yang dijual pada toko.")
            print("8. topup - Untuk menambahkan saldo dari user.")
            print("9. logout - Untuk logout dari akun yang digunakan.")
            print("10. exit - Untuk menyetop program.")
        elif userType.lower() == "user":
            print("================================ HELP ===================================")
            print("1. register - Untuk melakukan registrasi user baru")
            print("1. login - Untuk melakukan login ke dalam sistem")
            print("2. list_game_toko - Untuk melihat list game yang dijual pada toko")
            print("3. buy_game - Untuk membeli game yang terdapat pada toko")
            print("4. list_game - Untuk melihat game yang dimiliki User")
            print("5. search_my_game - Untuk mencari salah satu game yang dimiliki User")
            print("6. search_game_at_store - Untuk mencari sebuah game yang dijual pada toko")
            print("7. riwayat - Untuk melihat riwayat pembelian User")
        else:
            print("================================ HELP ===================================")
            print()
            print("---------------------------- Fitur Admin --------------------------------")
            print("================================ HELP ===================================")
            print("1. register - Untuk melakukan registrasi user baru.")
            print("2. login - Untuk melakukan login ke dalam sistem.")
            print("3. tambah_game - Untuk menambah game yang dijual pada toko.")
            print("4. ubah_game - Untuk mengubah data game yang dijual pada toko.")
            print("5. ubah_stok - Untuk mengubah stok game yang dijual pada toko.")
            print("6. list_game_toko - Untuk melihat daftar game yang dijual pada toko.")
            print("7. search_game_at_store - Untuk mencari sebuah game yang dijual pada toko.")
            print("8. topup - Untuk menambahkan saldo dari user.")
            print("9. logout - Untuk logout dari akun yang digunakan.")
            print("10. exit - Untuk menyetop program.")
            print()
            print("---------------------------- Fitur User ---------------------------------")
            print("1. register - Untuk melakukan registrasi user baru")
            print("2. login - Untuk melakukan login ke dalam sistem")
            print("3. list_game_toko - Untuk melihat list game yang dijual pada toko")
            print("4. buy_game - Untuk membeli game yang terdapat pada toko")
            print("5. list_game - Untuk melihat game yang dimiliki User")
            print("6. search_my_game - Untuk mencari salah satu game yang dimiliki User")
            print("7. search_game_at_store - Untuk mencari sebuah game yang dijual pada toko")
            print("8. riwayat - Untuk melihat riwayat pembelian User")
        print()
        print("Klik Enter untuk balik ke main menu.")
        input()
        stopShow = True